name: asl
description: An ASL Learning app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.4
  google_sign_in: ^6.0.2
  spaced_repetition: ^0.1.0
  flutter_svg: ^2.0.4
  url_strategy: ^0.2.0
  collection: ^1.17.0
  firebase_ui_firestore: ^1.2.10
  firebase_core: ^2.7.1
  firebase_auth: ^4.2.2
  cloud_firestore: ^4.4.4
  firebase_core_web: ^2.2.2
  firebase_auth_web: ^5.2.10
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
