name: asl
description: An ASL Learning app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^4.0.2
  provider: ^6.0.4
  cloud_firestore: ^4.0.2
  google_sign_in: ^5.4.2
  firebase_core: ^2.1.0
  spaced_repetition: ^0.1.0
  flutter_svg: ^1.1.6
  url_strategy: ^0.2.0
  snaplist: ^0.1.8
  image_sequence_animator: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
